### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by ryzokuken** [osdc/meetups#12]
Change date format from DD/MM/YY to YYYY-MM-DD.

**Comment by ryzokuken** [comment]
Comments? @darkHarry @vaibhavk

**Comment by darkHarry** [comment]
ISO 8601, yes, please.

**Comment by ryzokuken** [comment]
@darkHarry if nobody picks it up, I have an idea: compile a list of all FTOs before a meetup and announcing all of them *at* the meetup, assigning people right then and there.

**Comment by darkHarry** [comment]
That'd be great. One meetup for contributions.

**Comment by darkHarry** [comment]
I don't think announcing FTO's would get them done because only those who've been active would work on them and it won't get newcomers. I say this because even after promoting harbor and other projects no one has really done anything except for a few active ones. It'd be better if we conduct a device sprint regarding this once and then continue announcing FTOs in the subsequent meetups.

**Comment by ryzokuken** [comment]
Sure, but there's no harm in just announcing FTOs, right? Someone might jump in.

**Comment by darkHarry** [comment]
Shall we take this to CTC?

**Comment by ryzokuken** [comment]
@darkHarry sure.
